### ISSUE TITLE
Textos alternativos

### ISSUE THREAD

**Issue by castromaciel** [NicoAlmiron/proyecto-menu-grupo-2#36]
## Proceso
‌Página de inicio

## Resultado esperado
‌Se esperaba que la imagen contenga texto alternativo.

## Resultado actual
Actualmente la imagen no ‌posee texto alternativo.

## Captura
‌
![image](https://github.com/NicoAlmiron/proyecto-menu-grupo-2/assets/83432755/568f4744-2a5e-4927-9128-fadd4940671b)

https://github.com/NicoAlmiron/proyecto-menu-grupo-2/blob/f5ed8bbc2a7dbb25654db3c8a4a2316c11aed937/src/component/views/Inicio/InfoRestaurant.jsx#L10

Notas
Cualquier duda/consulta pueden contactarme vía mail, o por canal de slack de la comunidad de Rolling.

**Comment by NicoAlmiron** [comment]
se agrego el texto alternativo y se centro la imagen correspondiente al texto alternativo (ea78b4239aa15d1e8d0cffd83f989f34379eeeae)
