### ISSUE TITLE
Paginación en pedidos

### ISSUE THREAD

**Issue by castromaciel** [NicoAlmiron/proyecto-menu-grupo-2#37]
## Proceso

1. Ingresar como admin
2. Ver los pedidos pendientes

## Resultado esperado

Se espera que al mostrarse una paginación, cambien los elementos entre las paginas

## Resultado actual

La paginación no realiza ninguna acción

## Captura

https://github.com/NicoAlmiron/proyecto-menu-grupo-2/assets/83432755/56da4822-8829-47cb-8d3c-b7486002a3cc

## Notas

Cualquier duda/consulta pueden contactarme vía mail, o por canal de slack de la comunidad de Rolling.

**Comment by NicoAlmiron** [comment]
se corrigio el problema de la paginacion en pedidos (2e2aeb5acbcfdbf49d3e62b5da68fc8da7651c48)
