### ISSUE TITLE
Inconsistencia en idiomas

### ISSUE THREAD

**Issue by castromaciel** [NicoAlmiron/proyecto-menu-grupo-2#38]
## Proceso
1. Inicio‌
2. Ingresar
3. Crear cuenta

## Resultado esperado
Se esperaba que se unifique el idioma para no generar problemas para el usuario.

## Resultado actual
‌Actualmente se observan diferencias de idiomas en el label y el mensaje para el usuario.

## Captura
‌
![image](https://github.com/NicoAlmiron/proyecto-menu-grupo-2/assets/83432755/533eb09b-8270-4a39-929a-9e445a569d1d)

Notas
Cualquier duda/consulta pueden contactarme vía mail, o por canal de slack de la comunidad de Rolling

**Comment by NicoAlmiron** [comment]
se corrigio la inconcistencia del idioma, dejando exclucivamente el español como idioma para la interfas de usuario (ffb20581bcf3d07cbe76a7a652daaabbbc61b8db), (dc384f91bb8c11b0832291e37c28aba88fffbdc5)
