### ISSUE TITLE
Suspender usuario

### ISSUE THREAD

**Issue by castromaciel** [NicoAlmiron/proyecto-menu-grupo-2#39]
## Proceso

1. Ingresar como administrador
2. Intentar suspender un usuario
3. cancelar la suspensión
4. Intentar suspenderlo nuevamente

## Resultado esperado

Se espera que independientemente de las veces que se cancele una operación, permita realizarla posteriormente

## Resultado actual

Al cancelar una suspensión, la alerta no vuelve a aparecer

## Captura

https://github.com/NicoAlmiron/proyecto-menu-grupo-2/assets/83432755/cdc282ae-bd1d-4960-a438-d23ce586d774

## Notas

Cualquier duda/consulta pueden contactarme vía mail, o por canal de slack de la comunidad de Rolling.

**Comment by NicoAlmiron** [comment]
se corrigio la alerta correctamente (ab72180d9dc37305d6083c695d499e3c2715d879)
