### ISSUE TITLE
Suspendeer usuario Admin

### ISSUE THREAD

**Issue by castromaciel** [NicoAlmiron/proyecto-menu-grupo-2#40]
## Proceso

1. Iniciar sesión como admin
2. Intentar suspender un usuario

## Resultado esperado

El usuario administrador no deberia poder suspenderse a si mismo. Esto por temas de seguridad, dado que por equivocació se podría dañar la información.

## Resultado actual

Permite la suspensión del usuario admin

## Captura

https://github.com/NicoAlmiron/proyecto-menu-grupo-2/assets/83432755/6598d16a-ae27-4500-baa5-cc4763152645

## Notas

Cualquier duda/consulta pueden contactarme vía mail, o por canal de slack de la comunidad de Rolling.

**Comment by NicoAlmiron** [comment]
se cancelo la suspencion de cualquier administrador (ab72180d9dc37305d6083c695d499e3c2715d879)
