### ISSUE TITLE
Suspensión de un usuario

### ISSUE THREAD

**Issue by castromaciel** [NicoAlmiron/proyecto-menu-grupo-2#41]
## Proceso

1. Ingresar como administrador
2. Intentar suspender un usuario
3. Cancelar
4. Navegar hacia otro lado
5. Retornar a la suspesión

## Resultado esperado

Se espera que al cancelar una acción, la misma, no se ejecute.

## Resultado actual

Actualmente, se muestra el usuario suspendido a pesar de haber cancelado la acción

## Captura

https://github.com/NicoAlmiron/proyecto-menu-grupo-2/assets/83432755/a5355044-67ce-4f13-9440-c93b1070d112

## Notas

Cualquier duda/consulta pueden contactarme vía mail, o por canal de slack de la comunidad de Rolling.

**Comment by NicoAlmiron** [comment]
se corrigio la accion y ahora no se realiza la accion antes de ejecutar la alerta (ab72180d9dc37305d6083c695d499e3c2715d879)
