### ISSUE TITLE
Inicio de sesión usuario suspendido

### ISSUE THREAD

**Issue by castromaciel** [NicoAlmiron/proyecto-menu-grupo-2#42]
## Proceso

1. Crear un usuario
2. Iniciar sesion con admin
3. Suspender el usuario previamente creado
4. Cerrar Sesión de admin
5. Iniciar sesión con el usuario suspendido

## Resultado esperado

Como administrador, al suspender o eliminar un usario, se espera que el mismo no tenga acceso o no pueda completar el flujo de inicio de sesión correctamente

## Resultado actual

Permite iniciar sesión con un usuario suspendido

## Captura

<img width="1437" alt="Screenshot 2023-12-03 at 21 00 09" src="https://github.com/NicoAlmiron/proyecto-menu-grupo-2/assets/83432755/9560f100-6610-4e9c-872e-295238e94468">

<img width="1435" alt="image" src="https://github.com/NicoAlmiron/proyecto-menu-grupo-2/assets/83432755/04f5b0db-46c2-44aa-a7ae-bd4ed7cc6381">

<img width="1439" alt="image" src="https://github.com/NicoAlmiron/proyecto-menu-grupo-2/assets/83432755/59ed3c41-9e8e-475e-94df-334cceeb2306">

## Notas

Cualquier duda/consulta pueden contactarme vía mail, o por canal de slack de la comunidad de Rolling.

**Comment by NicoAlmiron** [comment]
se corrijio el problema de login en usuarios suspendidos (dbd4557026537d0744a172ba0dcde591c45f8aa1) (repositorio brack-end: https://github.com/NicoAlmiron/backend-proyecto-menu-grupo-2)
